version: "3.8"
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    ports:
      - 1433:1433
    volumes:
      - mssql_data:/var/opt/mssql
      - mssql_backup:/var/opt/mssql/backup
    environment:
      - TZ=Asia/Bangkok
      - ACCEPT_EULA=Y
      - MSSQL_PID=${MSSQL_PID}
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - MSSQL_BACKUP_DIR=/var/opt/mssql/backup
    networks:
      - mssql_network
volumes:
  mssql_data:
  mssql_backup:
networks:
  mssql_network:
