version: "3.8"
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    restart: always
    ports:
      - 1433:1433
    volumes:
      - mssql_data:/var/opt/mssql
      - mssql_backup:/var/opt/mssql/backup
    environment:
      - TZ=Asia/Bangkok
      - MSSQL_AGENT_ENABLED=true
      - MSSQL_COLLATION=THAI_CI_AI
      - ACCEPT_EULA=Y
      - MSSQL_PID=${MSSQL_PID}
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - MSSQL_BACKUP_DIR=/var/opt/mssql/backup
    networks:
      - mssql_network
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
volumes:
  mssql_data:
  mssql_backup:
networks:
  mssql_network:
